language: python
sudo: false

python:
    - 2.7
    - 3.5
    - 3.6

install:
    - travis_retry pip install flake8
    - travis_retry pip install virtualenv
    - virtualenv ./.venv
    - ./.venv/bin/python -VV
    - ./.venv/bin/python setup.py install
    - ./.venv/bin/pip freeze

script:
    - flake8
